### ISSUE TITLE
More Mux pattern options (SHIFTREG_ABC_BIN_DE)?

### ISSUE THREAD

**Issue by BjarneJensen** [TheLogicMaster/ESP-LED-Matrix-Display#4]
The precompiled binary seems to work for my esp8266 with pxmatrix, however the mux pattern appears to be wrong. It should be set to   `SHIFTREG_ABC_BIN_DE` for my panel. I am so far unable to rebuild with arduino or platformio. Is there a way to add this mux pattern setting via webbrowser without rebuilding? Thanks

**Comment by BjarneJensen** [comment]
I just ended up editing the config directly in the pxmatrix lib header

**Comment by TheLogicMaster** [comment]
Not sure why two of the mux patterns aren't available from the dashboard, but presumably it's just a few lines of JS and C++ to fix.

**Comment by BjarneJensen** [comment]
Yeah it should be an easy enough addition. I tried editing the settings.vue, but had trouble rebuilding the dashboard, so I just renamed the patterns in the pxmatrix lib. I have a weird display evidently. Thanks for your work.
